server:
  port: 20077

spring:
  datasource: # 数据源的配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql的数据库驱动类名称
    url: jdbc:mysql://127.0.0.1:3306/wechat-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # username: nacos
        # password: nacos

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: zrn
    password: zrn1996
    virtual-host: wechat-dev